// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "KyruusAppointments/models"
)

// NewCreateAppointmentParams creates a new CreateAppointmentParams object
// no default values defined in spec.
func NewCreateAppointmentParams() CreateAppointmentParams {

	return CreateAppointmentParams{}
}

// CreateAppointmentParams contains all the bound params for the create appointment operation
// typically these are obtained from a http.Request
//
// swagger:parameters CreateAppointment
type CreateAppointmentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	CreateAppointment *models.Appointment
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateAppointmentParams() beforehand.
func (o *CreateAppointmentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Appointment
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("createAppointment", "body"))
			} else {
				res = append(res, errors.NewParseError("createAppointment", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.CreateAppointment = &body
			}
		}
	} else {
		res = append(res, errors.Required("createAppointment", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
