// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteAppointmentHandlerFunc turns a function with the right signature into a delete appointment handler
type DeleteAppointmentHandlerFunc func(DeleteAppointmentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAppointmentHandlerFunc) Handle(params DeleteAppointmentParams) middleware.Responder {
	return fn(params)
}

// DeleteAppointmentHandler interface for that can handle valid delete appointment params
type DeleteAppointmentHandler interface {
	Handle(DeleteAppointmentParams) middleware.Responder
}

// NewDeleteAppointment creates a new http.Handler for the delete appointment operation
func NewDeleteAppointment(ctx *middleware.Context, handler DeleteAppointmentHandler) *DeleteAppointment {
	return &DeleteAppointment{Context: ctx, Handler: handler}
}

/*DeleteAppointment swagger:route DELETE /appointments deleteAppointment

DeleteAppointment delete appointment API

*/
type DeleteAppointment struct {
	Context *middleware.Context
	Handler DeleteAppointmentHandler
}

func (o *DeleteAppointment) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteAppointmentParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
