// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDoctorHandlerFunc turns a function with the right signature into a delete doctor handler
type DeleteDoctorHandlerFunc func(DeleteDoctorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDoctorHandlerFunc) Handle(params DeleteDoctorParams) middleware.Responder {
	return fn(params)
}

// DeleteDoctorHandler interface for that can handle valid delete doctor params
type DeleteDoctorHandler interface {
	Handle(DeleteDoctorParams) middleware.Responder
}

// NewDeleteDoctor creates a new http.Handler for the delete doctor operation
func NewDeleteDoctor(ctx *middleware.Context, handler DeleteDoctorHandler) *DeleteDoctor {
	return &DeleteDoctor{Context: ctx, Handler: handler}
}

/*DeleteDoctor swagger:route DELETE /doctors/{doctorId} deleteDoctor

DeleteDoctor delete doctor API

*/
type DeleteDoctor struct {
	Context *middleware.Context
	Handler DeleteDoctorHandler
}

func (o *DeleteDoctor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDoctorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
