// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "KyruusAppointments/models"
)

// GetAppointmentsOKCode is the HTTP code returned for type GetAppointmentsOK
const GetAppointmentsOKCode int = 200

/*GetAppointmentsOK OK

swagger:response getAppointmentsOK
*/
type GetAppointmentsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Appointment `json:"body,omitempty"`
}

// NewGetAppointmentsOK creates GetAppointmentsOK with default headers values
func NewGetAppointmentsOK() *GetAppointmentsOK {

	return &GetAppointmentsOK{}
}

// WithPayload adds the payload to the get appointments o k response
func (o *GetAppointmentsOK) WithPayload(payload []*models.Appointment) *GetAppointmentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments o k response
func (o *GetAppointmentsOK) SetPayload(payload []*models.Appointment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Appointment, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAppointmentsNotFoundCode is the HTTP code returned for type GetAppointmentsNotFound
const GetAppointmentsNotFoundCode int = 404

/*GetAppointmentsNotFound Doctor not found

swagger:response getAppointmentsNotFound
*/
type GetAppointmentsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.BadRequest `json:"body,omitempty"`
}

// NewGetAppointmentsNotFound creates GetAppointmentsNotFound with default headers values
func NewGetAppointmentsNotFound() *GetAppointmentsNotFound {

	return &GetAppointmentsNotFound{}
}

// WithPayload adds the payload to the get appointments not found response
func (o *GetAppointmentsNotFound) WithPayload(payload *models.BadRequest) *GetAppointmentsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get appointments not found response
func (o *GetAppointmentsNotFound) SetPayload(payload *models.BadRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAppointmentsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
