// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAppointmentsHandlerFunc turns a function with the right signature into a get appointments handler
type GetAppointmentsHandlerFunc func(GetAppointmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAppointmentsHandlerFunc) Handle(params GetAppointmentsParams) middleware.Responder {
	return fn(params)
}

// GetAppointmentsHandler interface for that can handle valid get appointments params
type GetAppointmentsHandler interface {
	Handle(GetAppointmentsParams) middleware.Responder
}

// NewGetAppointments creates a new http.Handler for the get appointments operation
func NewGetAppointments(ctx *middleware.Context, handler GetAppointmentsHandler) *GetAppointments {
	return &GetAppointments{Context: ctx, Handler: handler}
}

/*GetAppointments swagger:route GET /appointments/{doctorId} getAppointments

GetAppointments get appointments API

*/
type GetAppointments struct {
	Context *middleware.Context
	Handler GetAppointmentsHandler
}

func (o *GetAppointments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAppointmentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
