// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDoctorHandlerFunc turns a function with the right signature into a get doctor handler
type GetDoctorHandlerFunc func(GetDoctorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDoctorHandlerFunc) Handle(params GetDoctorParams) middleware.Responder {
	return fn(params)
}

// GetDoctorHandler interface for that can handle valid get doctor params
type GetDoctorHandler interface {
	Handle(GetDoctorParams) middleware.Responder
}

// NewGetDoctor creates a new http.Handler for the get doctor operation
func NewGetDoctor(ctx *middleware.Context, handler GetDoctorHandler) *GetDoctor {
	return &GetDoctor{Context: ctx, Handler: handler}
}

/*GetDoctor swagger:route GET /doctors/{doctorId} getDoctor

GetDoctor get doctor API

*/
type GetDoctor struct {
	Context *middleware.Context
	Handler GetDoctorHandler
}

func (o *GetDoctor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDoctorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
