// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewKyruusAPI creates a new Kyruus instance
func NewKyruusAPI(spec *loads.Document) *KyruusAPI {
	return &KyruusAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		CreateAppointmentHandler: CreateAppointmentHandlerFunc(func(params CreateAppointmentParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateAppointment has not yet been implemented")
		}),
		CreateDoctorHandler: CreateDoctorHandlerFunc(func(params CreateDoctorParams) middleware.Responder {
			return middleware.NotImplemented("operation CreateDoctor has not yet been implemented")
		}),
		DeleteAppointmentHandler: DeleteAppointmentHandlerFunc(func(params DeleteAppointmentParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteAppointment has not yet been implemented")
		}),
		DeleteDoctorHandler: DeleteDoctorHandlerFunc(func(params DeleteDoctorParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteDoctor has not yet been implemented")
		}),
		GetAppointmentsHandler: GetAppointmentsHandlerFunc(func(params GetAppointmentsParams) middleware.Responder {
			return middleware.NotImplemented("operation GetAppointments has not yet been implemented")
		}),
		GetDoctorHandler: GetDoctorHandlerFunc(func(params GetDoctorParams) middleware.Responder {
			return middleware.NotImplemented("operation GetDoctor has not yet been implemented")
		}),
		UpdateDoctorHandler: UpdateDoctorHandlerFunc(func(params UpdateDoctorParams) middleware.Responder {
			return middleware.NotImplemented("operation UpdateDoctor has not yet been implemented")
		}),
	}
}

/*KyruusAPI Kyruus Doctor Appointments */
type KyruusAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// CreateAppointmentHandler sets the operation handler for the create appointment operation
	CreateAppointmentHandler CreateAppointmentHandler
	// CreateDoctorHandler sets the operation handler for the create doctor operation
	CreateDoctorHandler CreateDoctorHandler
	// DeleteAppointmentHandler sets the operation handler for the delete appointment operation
	DeleteAppointmentHandler DeleteAppointmentHandler
	// DeleteDoctorHandler sets the operation handler for the delete doctor operation
	DeleteDoctorHandler DeleteDoctorHandler
	// GetAppointmentsHandler sets the operation handler for the get appointments operation
	GetAppointmentsHandler GetAppointmentsHandler
	// GetDoctorHandler sets the operation handler for the get doctor operation
	GetDoctorHandler GetDoctorHandler
	// UpdateDoctorHandler sets the operation handler for the update doctor operation
	UpdateDoctorHandler UpdateDoctorHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *KyruusAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *KyruusAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *KyruusAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *KyruusAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *KyruusAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *KyruusAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *KyruusAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the KyruusAPI
func (o *KyruusAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.CreateAppointmentHandler == nil {
		unregistered = append(unregistered, "CreateAppointmentHandler")
	}

	if o.CreateDoctorHandler == nil {
		unregistered = append(unregistered, "CreateDoctorHandler")
	}

	if o.DeleteAppointmentHandler == nil {
		unregistered = append(unregistered, "DeleteAppointmentHandler")
	}

	if o.DeleteDoctorHandler == nil {
		unregistered = append(unregistered, "DeleteDoctorHandler")
	}

	if o.GetAppointmentsHandler == nil {
		unregistered = append(unregistered, "GetAppointmentsHandler")
	}

	if o.GetDoctorHandler == nil {
		unregistered = append(unregistered, "GetDoctorHandler")
	}

	if o.UpdateDoctorHandler == nil {
		unregistered = append(unregistered, "UpdateDoctorHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *KyruusAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *KyruusAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *KyruusAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *KyruusAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *KyruusAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *KyruusAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the kyruus API
func (o *KyruusAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *KyruusAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/appointments"] = NewCreateAppointment(o.context, o.CreateAppointmentHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/doctors"] = NewCreateDoctor(o.context, o.CreateDoctorHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/appointments"] = NewDeleteAppointment(o.context, o.DeleteAppointmentHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/doctors/{doctorId}"] = NewDeleteDoctor(o.context, o.DeleteDoctorHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/appointments/{doctorId}"] = NewGetAppointments(o.context, o.GetAppointmentsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/doctors/{doctorId}"] = NewGetDoctor(o.context, o.GetDoctorHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/doctors/{doctorId}"] = NewUpdateDoctor(o.context, o.UpdateDoctorHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *KyruusAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *KyruusAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *KyruusAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *KyruusAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
