// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDoctorHandlerFunc turns a function with the right signature into a update doctor handler
type UpdateDoctorHandlerFunc func(UpdateDoctorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDoctorHandlerFunc) Handle(params UpdateDoctorParams) middleware.Responder {
	return fn(params)
}

// UpdateDoctorHandler interface for that can handle valid update doctor params
type UpdateDoctorHandler interface {
	Handle(UpdateDoctorParams) middleware.Responder
}

// NewUpdateDoctor creates a new http.Handler for the update doctor operation
func NewUpdateDoctor(ctx *middleware.Context, handler UpdateDoctorHandler) *UpdateDoctor {
	return &UpdateDoctor{Context: ctx, Handler: handler}
}

/*UpdateDoctor swagger:route PUT /doctors/{doctorId} updateDoctor

UpdateDoctor update doctor API

*/
type UpdateDoctor struct {
	Context *middleware.Context
	Handler UpdateDoctorHandler
}

func (o *UpdateDoctor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateDoctorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
