// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "KyruusAppointments/models"
)

// NewUpdateDoctorParams creates a new UpdateDoctorParams object
// no default values defined in spec.
func NewUpdateDoctorParams() UpdateDoctorParams {

	return UpdateDoctorParams{}
}

// UpdateDoctorParams contains all the bound params for the update doctor operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateDoctor
type UpdateDoctorParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	UpdateDoctorInput *models.Doctor
	/*
	  Required: true
	  In: path
	*/
	DoctorID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateDoctorParams() beforehand.
func (o *UpdateDoctorParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Doctor
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("updateDoctorInput", "body"))
			} else {
				res = append(res, errors.NewParseError("updateDoctorInput", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.UpdateDoctorInput = &body
			}
		}
	} else {
		res = append(res, errors.Required("updateDoctorInput", "body"))
	}
	rDoctorID, rhkDoctorID, _ := route.Params.GetOK("doctorId")
	if err := o.bindDoctorID(rDoctorID, rhkDoctorID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDoctorID binds and validates parameter DoctorID from path.
func (o *UpdateDoctorParams) bindDoctorID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("doctorId", "path", "int64", raw)
	}
	o.DoctorID = value

	return nil
}
