// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Kyruus Doctor Appointments",
    "title": "Kyruus",
    "version": "0.1.0"
  },
  "paths": {
    "/appointments": {
      "post": {
        "operationId": "CreateAppointment",
        "parameters": [
          {
            "name": "CreateAppointment",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Appointment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "Appointment could not be created",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteAppointment",
        "parameters": [
          {
            "name": "DeleteAppointment",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Appointment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Appointment does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/appointments/{doctorId}": {
      "get": {
        "operationId": "GetAppointments",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Appointment"
              }
            }
          },
          "404": {
            "description": "Doctor not found",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/doctors": {
      "post": {
        "operationId": "CreateDoctor",
        "parameters": [
          {
            "name": "CreateDoctorInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "Doctor with id already exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/doctors/{doctorId}": {
      "get": {
        "operationId": "GetDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          },
          "404": {
            "description": "Doctor not found",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "put": {
        "operationId": "UpdateDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          },
          {
            "name": "UpdateDoctorInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Doctor does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Doctor does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Appointment": {
      "description": "A doctor's appointment",
      "type": "object",
      "required": [
        "doctorId",
        "locationId",
        "day",
        "time"
      ],
      "properties": {
        "day": {
          "type": "string"
        },
        "doctorId": {
          "type": "integer"
        },
        "locationId": {
          "type": "string"
        },
        "time": {
          "type": "integer"
        }
      }
    },
    "AppointmentList": {
      "description": "A list of appointments",
      "type": "object",
      "required": [
        "list"
      ],
      "properties": {
        "list": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/Appointment"
          }
        }
      }
    },
    "BadRequest": {
      "description": "Bad Request object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Doctor": {
      "description": "A doctor",
      "type": "object",
      "required": [
        "name",
        "id",
        "locations",
        "schedule"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "locations": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Appointment"
          }
        }
      }
    },
    "NotFound": {
      "description": "Not Found object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Time": {
      "description": "The time value representing a doctor's appointment",
      "type": "object",
      "required": [
        "day",
        "hour"
      ],
      "properties": {
        "day": {
          "type": "string"
        },
        "hour": {
          "type": "integer"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Kyruus Doctor Appointments",
    "title": "Kyruus",
    "version": "0.1.0"
  },
  "paths": {
    "/appointments": {
      "post": {
        "operationId": "CreateAppointment",
        "parameters": [
          {
            "name": "CreateAppointment",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Appointment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "Appointment could not be created",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteAppointment",
        "parameters": [
          {
            "name": "DeleteAppointment",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Appointment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Appointment does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/appointments/{doctorId}": {
      "get": {
        "operationId": "GetAppointments",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Appointment"
              }
            }
          },
          "404": {
            "description": "Doctor not found",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/doctors": {
      "post": {
        "operationId": "CreateDoctor",
        "parameters": [
          {
            "name": "CreateDoctorInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "Doctor with id already exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    },
    "/doctors/{doctorId}": {
      "get": {
        "operationId": "GetDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          },
          "404": {
            "description": "Doctor not found",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "put": {
        "operationId": "UpdateDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          },
          {
            "name": "UpdateDoctorInput",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Doctor"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Doctor does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      },
      "delete": {
        "operationId": "DeleteDoctor",
        "parameters": [
          {
            "type": "integer",
            "name": "doctorId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "404": {
            "description": "Doctor does not exists",
            "schema": {
              "$ref": "#/definitions/BadRequest"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Appointment": {
      "description": "A doctor's appointment",
      "type": "object",
      "required": [
        "doctorId",
        "locationId",
        "day",
        "time"
      ],
      "properties": {
        "day": {
          "type": "string"
        },
        "doctorId": {
          "type": "integer"
        },
        "locationId": {
          "type": "string"
        },
        "time": {
          "type": "integer"
        }
      }
    },
    "AppointmentList": {
      "description": "A list of appointments",
      "type": "object",
      "required": [
        "list"
      ],
      "properties": {
        "list": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/Appointment"
          }
        }
      }
    },
    "BadRequest": {
      "description": "Bad Request object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Doctor": {
      "description": "A doctor",
      "type": "object",
      "required": [
        "name",
        "id",
        "locations",
        "schedule"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "locations": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "schedule": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Appointment"
          }
        }
      }
    },
    "NotFound": {
      "description": "Not Found object",
      "type": "object",
      "properties": {
        "code": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Time": {
      "description": "The time value representing a doctor's appointment",
      "type": "object",
      "required": [
        "day",
        "hour"
      ],
      "properties": {
        "day": {
          "type": "string"
        },
        "hour": {
          "type": "integer"
        }
      }
    }
  }
}`))
}
